/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/shelves.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[2,2,-4]} scale={[1, 0.19, 7.09]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[2,-2,-4]} scale={[1, 0.19, 7.09]} />
    </group>
  )
}

useGLTF.preload('/shelves.gltf')
